---
- hosts: containers
  become: true
  tasks:
    - name: copy service
      copy:
        src: ../../source/adservice
        dest: /opt/
    - name: build docker image
      command: docker build /opt/adservice/. -t adservice:latest
