---
- hosts: containers
  become: true
  tasks:
    - name: copy service
      copy:
        src: ../../source/currencyservice
        dest: /opt/
    - name: build docker image
      command: docker build /opt/currencyservice/. -t currencyservice:latest
