---
- hosts: containers
  become: true
  tasks:
    - name: copy service
      copy:
        src: ../../source/frontend
        dest: /opt/
    - name: build docker image
      command: docker build /opt/frontend/. -t frontend:latest
