---
- hosts: containers
  become: true
  tasks:
    - name: copy service
      copy:
        src: ../../source/loadgenerator
        dest: /opt/
    - name: build docker image
      command: docker build /opt/loadgenerator/. -t loadgenerator:latest
