---
- hosts: containers
  become: true
  tasks:
    - name: copy service
      copy:
        src: ../../source/productcatalogservice
        dest: /opt/
    - name: build docker image
      command: docker build /opt/productcatalogservice/. -t productcatalogservice:latest
